version: 2
jobs:
  build:
    working_directory: ~/mern-starter
    # The primary container is an instance of the first list image listed. Your {% comment %} TODO: Job {% endcomment %}build commands run in this container.
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      
      - run:
          name: Create Virtual Environment
          command: |
            python3 -m venv dq
      
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get install unixodbc-dev
            . dq/bin/activate
            pip3 install --upgrade pip
            pip3 install -r requirements.txt 
            
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
          
          
      - save_cache:
          - save_cache:
            paths:
              - ./venv
            key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            gunicorn --bind 127.0.0.1:8000 app
            background: true
          - sleep 100  

      - run:
        name: Run Tests
        command: nosetests test_flask.py
