version: 2
jobs:
  build:
    working_directory: ~/ci
    docker:
      - image: circleci/python:3.5.2-browsers
    steps:
      - checkout
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt    
    
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"
      - run:
          command: |
            . venv/bin/activate
            python app.py

      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1

